name: energy_monitor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  databases:
    path: packages/databases
  equatable: ^2.0.7
  energy_api_client:
    path: packages/energy_api_client
  energy_repository:
    path: packages/energy_repository
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fl_chart: ^0.70.2
  internet_connection_checker_plus: ^2.7.0

dev_dependencies:
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
