name: databases
description: "A base crud operations for sqlite databases"
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.6.0

dependencies:
  drift: ^2.25.1
  sqlite3_flutter_libs: ^0.5.30
  meta: ^1.9.1
  path_provider: ^2.1.5
  path: ^1.9.0

dev_dependencies:
  drift_dev: ^2.25.2
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

